using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using MassTransit;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using VideoOzet.Business.Events;
using VideoOzet.Business.Interfaces;
using VideoOzet.Data.Context;
using VideoOzet.Data.Entities;
using VideoOzet.Data.Enums;
using VideoOzet.Worker.Consumers;
using Xunit;

using Moq.EntityFrameworkCore;
using System.Collections.Generic;

namespace VideoOzet.UnitTests.Worker;

public class ExtractTranscriptConsumerTests
{
    [Fact]
    public async Task Consume_ShouldProcessVideo_WhenLockIsAcquiredAndEverythingSucceeds()
    {
        // Arrange
        var videoId = Guid.NewGuid();
        var egitimId = Guid.NewGuid();
        
        var egitim = new Egitim
        {
            Id = egitimId,
            Ad = "Test Egitim"
        };

        var video = new Video
        {
            Id = videoId,
            EgitimId = egitimId,
            Egitim = egitim,
            Baslik = "Test Video",
            DosyaYolu = "test_video.mp4",
            IslemDurumu = VideoIslemDurumu.Bekliyor
        };

        var dbContextMock = new Mock<AppDbContext>(new DbContextOptions<AppDbContext>());
        var videoDbSetMock = new Mock<DbSet<Video>>();
        
        dbContextMock.Setup(x => x.Videolar).ReturnsDbSet(new List<Video> { video }, videoDbSetMock);
        
        videoDbSetMock.Setup(x => x.FindAsync(It.IsAny<object[]>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((object[] keyValues, CancellationToken token) => 
                (Guid)keyValues[0] == videoId ? video : null);

        dbContextMock.Setup(x => x.Egitimler).ReturnsDbSet(new List<Egitim> { egitim });
        
        var savedTranscripts = new List<VideoTranscript>();
        dbContextMock.Setup(x => x.VideoTranscripts).ReturnsDbSet(savedTranscripts);

        var loggerMock = new Mock<ILogger<ExtractTranscriptConsumer>>();
        var cacheServiceMock = new Mock<ICacheService>();
        var fileStorageMock = new Mock<IFileStorageService>();
        var audioExtractorMock = new Mock<IAudioExtractor>();
        var sttProviderMock = new Mock<ISttProvider>();
        var publishEndpointMock = new Mock<IPublishEndpoint>();

        var consumer = new ExtractTranscriptConsumer(
            loggerMock.Object,
            cacheServiceMock.Object,
            fileStorageMock.Object,
            audioExtractorMock.Object,
            sttProviderMock.Object,
            dbContextMock.Object,
            publishEndpointMock.Object);

        var contextMock = new Mock<ConsumeContext<VideoUploadedEvent>>();
        contextMock.Setup(c => c.Message).Returns(new VideoUploadedEvent
        {
            VideoId = videoId,
            EgitimId = egitimId,
            DosyaYolu = "test_video.mp4"
        });
        contextMock.Setup(c => c.CancellationToken).Returns(CancellationToken.None);

        // Mocks setup
        cacheServiceMock
            .Setup(c => c.SetIfNotExistsAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<TimeSpan>()))
            .ReturnsAsync(true); // Lock acquired

        fileStorageMock
            .Setup(f => f.DownloadFileAsync(It.IsAny<string>()))
            .ReturnsAsync(new MemoryStream(new byte[] { 1, 2, 3 })); // Dummy stream

        audioExtractorMock
            .Setup(a => a.ExtractAudioAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<string, string, CancellationToken>((videoPath, audioPath, ct) =>
            {
                // Consumer expects this file to exist after extraction
                Directory.CreateDirectory(Path.GetDirectoryName(audioPath)!);
                File.WriteAllBytes(audioPath, new byte[] { 0xFF, 0xFB, 0x90 }); // Dummy mp3 bytes
            })
            .ReturnsAsync(true); // Extraction succeeds

        sttProviderMock
            .Setup(s => s.TranscribeAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("This is a dummy transcript text generated by mock STT.");

        // Act
        await consumer.Consume(contextMock.Object);

        // Assert
        video.IslemDurumu.Should().Be(VideoIslemDurumu.SttTamamlandi);
        
        dbContextMock.Verify(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Exactly(2));

        publishEndpointMock.Verify(
            p => p.Publish(It.Is<TranscriptReadyEvent>(e => e.VideoId == videoId), It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task Consume_ShouldSkipProcessing_WhenLockIsNotAcquired()
    {
        // Arrange - Idempotency testi: Aynı mesaj iki kez gelirse ikincisi işlenmemeli
        var videoId = Guid.NewGuid();
        var egitimId = Guid.NewGuid();

        var dbContextMock = new Mock<AppDbContext>(new DbContextOptions<AppDbContext>());
        var loggerMock = new Mock<ILogger<ExtractTranscriptConsumer>>();
        var cacheServiceMock = new Mock<ICacheService>();
        var fileStorageMock = new Mock<IFileStorageService>();
        var audioExtractorMock = new Mock<IAudioExtractor>();
        var sttProviderMock = new Mock<ISttProvider>();
        var publishEndpointMock = new Mock<IPublishEndpoint>();

        // Lock zaten başka bir Worker tarafından alınmış
        cacheServiceMock
            .Setup(c => c.SetIfNotExistsAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<TimeSpan>()))
            .ReturnsAsync(false); // Lock NOT acquired

        var consumer = new ExtractTranscriptConsumer(
            loggerMock.Object,
            cacheServiceMock.Object,
            fileStorageMock.Object,
            audioExtractorMock.Object,
            sttProviderMock.Object,
            dbContextMock.Object,
            publishEndpointMock.Object);

        var contextMock = new Mock<ConsumeContext<VideoUploadedEvent>>();
        contextMock.Setup(c => c.Message).Returns(new VideoUploadedEvent
        {
            VideoId = videoId,
            EgitimId = egitimId,
            DosyaYolu = "test_video.mp4"
        });

        // Act
        await consumer.Consume(contextMock.Object);

        // Assert - Hiçbir iş yapılmamalı
        fileStorageMock.Verify(f => f.DownloadFileAsync(It.IsAny<string>()), Times.Never);
        audioExtractorMock.Verify(a => a.ExtractAudioAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
        sttProviderMock.Verify(s => s.TranscribeAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
        publishEndpointMock.Verify(p => p.Publish(It.IsAny<TranscriptReadyEvent>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Consume_ShouldReturnEarly_WhenVideoNotFoundInDb()
    {
        // Arrange - Veritabanında olmayan bir video ID'si gelirse
        var videoId = Guid.NewGuid();
        var egitimId = Guid.NewGuid();

        var dbContextMock = new Mock<AppDbContext>(new DbContextOptions<AppDbContext>());
        var videoDbSetMock = new Mock<DbSet<Video>>();

        dbContextMock.Setup(x => x.Videolar).ReturnsDbSet(new List<Video>(), videoDbSetMock);

        // FindAsync null döndürsün
        videoDbSetMock.Setup(x => x.FindAsync(It.IsAny<object[]>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Video?)null);

        var loggerMock = new Mock<ILogger<ExtractTranscriptConsumer>>();
        var cacheServiceMock = new Mock<ICacheService>();
        var fileStorageMock = new Mock<IFileStorageService>();
        var audioExtractorMock = new Mock<IAudioExtractor>();
        var sttProviderMock = new Mock<ISttProvider>();
        var publishEndpointMock = new Mock<IPublishEndpoint>();

        // Lock alınsın ama video bulunamasın
        cacheServiceMock
            .Setup(c => c.SetIfNotExistsAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<TimeSpan>()))
            .ReturnsAsync(true);

        var consumer = new ExtractTranscriptConsumer(
            loggerMock.Object,
            cacheServiceMock.Object,
            fileStorageMock.Object,
            audioExtractorMock.Object,
            sttProviderMock.Object,
            dbContextMock.Object,
            publishEndpointMock.Object);

        var contextMock = new Mock<ConsumeContext<VideoUploadedEvent>>();
        contextMock.Setup(c => c.Message).Returns(new VideoUploadedEvent
        {
            VideoId = videoId,
            EgitimId = egitimId,
            DosyaYolu = "test_video.mp4"
        });
        contextMock.Setup(c => c.CancellationToken).Returns(CancellationToken.None);

        // Act
        await consumer.Consume(contextMock.Object);

        // Assert - Dosya indirme ve STT çağrılmamalı
        fileStorageMock.Verify(f => f.DownloadFileAsync(It.IsAny<string>()), Times.Never);
        sttProviderMock.Verify(s => s.TranscribeAsync(It.IsAny<Stream>(), It.IsAny<string>(), It.IsAny<CancellationToken>()), Times.Never);
        publishEndpointMock.Verify(p => p.Publish(It.IsAny<TranscriptReadyEvent>(), It.IsAny<CancellationToken>()), Times.Never);
    }
}
