// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using VideoOzet.Data.Context;

#nullable disable

namespace VideoOzet.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909080505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoOzet.Data.Entities.ContentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("durum");

                    b.Property<Guid>("EgitimId")
                        .HasColumnType("uuid")
                        .HasColumnName("egitim_id");

                    b.Property<string>("HedefKitle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hedef_kitle");

                    b.Property<string>("HedefUzunluk")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hedef_uzunluk");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("konu");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tamamlanma_tarihi");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("idx_content_requests_durum");

                    b.HasIndex("EgitimId")
                        .HasDatabaseName("idx_content_requests_egitim_id");

                    b.ToTable("content_requests", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.Egitim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<int>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("durum");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<int>("IslenmiVideoSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("islenmi_video_sayisi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ToplamVideoSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("toplam_video_sayisi");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("idx_egitimler_durum");

                    b.HasIndex("OlusturmaTarihi")
                        .IsDescending()
                        .HasDatabaseName("idx_egitimler_olusturma");

                    b.ToTable("egitimler", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.EndpointLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Query")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("query");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_email");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_endpoint_logs_created_at");

                    b.HasIndex("Path")
                        .HasDatabaseName("idx_endpoint_logs_path");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("idx_endpoint_logs_status_code");

                    b.ToTable("endpoint_logs", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.FunctionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("InputType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("input_type");

                    b.Property<string>("InputValue")
                        .HasColumnType("text")
                        .HasColumnName("input_value");

                    b.Property<int>("LineNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("line_number");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("method_name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Error")
                        .HasColumnName("severity");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_function_logs_created_at");

                    b.HasIndex("ErrorCode")
                        .HasDatabaseName("idx_function_logs_error_code");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_function_logs_severity");

                    b.HasIndex("ClassName", "MethodName")
                        .HasDatabaseName("idx_function_logs_class_method");

                    b.ToTable("function_logs", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.GeneratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArastirmaOzeti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arastirma_ozeti");

                    b.Property<Guid>("ContentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_request_id");

                    b.Property<string>("KullanilanKaynaklar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("kullanilan_kaynaklar");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("llm_model");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TokenKullanimi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_kullanimi");

                    b.Property<int>("UretimSuresiMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("uretim_suresi_ms");

                    b.Property<string>("VideoPlani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_plani");

                    b.HasKey("Id");

                    b.HasIndex("ContentRequestId")
                        .IsUnique()
                        .HasDatabaseName("idx_generated_contents_request_id");

                    b.ToTable("generated_contents", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.PipelineLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Asama")
                        .HasColumnType("integer")
                        .HasColumnName("asama");

                    b.Property<DateTime>("BaslangicZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("baslangic_zamani")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bitis_zamani");

                    b.Property<string>("CiktiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("cikti_metadata");

                    b.Property<Guid?>("ContentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum");

                    b.Property<Guid?>("EgitimId")
                        .HasColumnType("uuid")
                        .HasColumnName("egitim_id");

                    b.Property<string>("GirdiMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("girdi_metadata");

                    b.Property<string>("HataDetayi")
                        .HasColumnType("text")
                        .HasColumnName("hata_detayi");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("text")
                        .HasColumnName("hata_mesaji");

                    b.Property<int?>("SureMs")
                        .HasColumnType("integer")
                        .HasColumnName("sure_ms");

                    b.Property<string>("TraceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("Asama")
                        .HasDatabaseName("idx_pipeline_logs_asama");

                    b.HasIndex("ContentRequestId")
                        .HasDatabaseName("idx_pipeline_logs_content_request");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_pipeline_logs_created_at");

                    b.HasIndex("Durum")
                        .HasDatabaseName("idx_pipeline_logs_durum");

                    b.HasIndex("EgitimId")
                        .HasDatabaseName("idx_pipeline_logs_egitim_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("idx_pipeline_logs_video_id");

                    b.ToTable("pipeline_logs", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.QcResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BelirsizSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("belirsiz_sayisi");

                    b.Property<Guid>("ContentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_request_id");

                    b.Property<int>("DesteklenenSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("desteklenen_sayisi");

                    b.Property<int>("DesteklenmeyenSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("desteklenmeyen_sayisi");

                    b.Property<string>("DetayliRapor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("detayli_rapor");

                    b.Property<decimal>("GuvenSkorYuzde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("guven_skor_yuzde");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ToplamIddiaSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("toplam_iddia_sayisi");

                    b.HasKey("Id");

                    b.HasIndex("ContentRequestId")
                        .IsUnique()
                        .HasDatabaseName("idx_qc_results_request_id");

                    b.ToTable("qc_results", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("baslik");

                    b.Property<long>("DosyaBoyutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("dosya_boyutu");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<Guid>("EgitimId")
                        .HasColumnType("uuid")
                        .HasColumnName("egitim_id");

                    b.Property<int>("IslemDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("islem_durumu");

                    b.Property<DateTime?>("IslemTamamlanmaTarihi")
                        .HasColumnType("timestamptz")
                        .HasColumnName("islem_tamamlanma_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SesYolu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ses_yolu");

                    b.Property<int>("Sira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sira");

                    b.Property<TimeSpan?>("Sure")
                        .HasColumnType("interval")
                        .HasColumnName("sure");

                    b.HasKey("Id");

                    b.HasIndex("EgitimId")
                        .HasDatabaseName("idx_videolar_egitim_id");

                    b.HasIndex("IslemDurumu")
                        .HasDatabaseName("idx_videolar_durum");

                    b.HasIndex("EgitimId", "Sira")
                        .HasDatabaseName("idx_videolar_egitim_sira");

                    b.ToTable("videolar", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.VideoChunkDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EgitimId")
                        .HasColumnType("uuid")
                        .HasColumnName("egitim_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("EndTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("end_time_ms");

                    b.Property<int>("StartTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("EgitimId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("video_chunk_documents", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.VideoSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("KonuBasliklari")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("konu_basliklari");

                    b.Property<string>("KonuEtiketleri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("konu_etiketleri");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("llm_model");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OzetMetni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ozet_metni");

                    b.Property<int>("TokenKullanimi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_kullanimi");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("idx_video_summaries_video_id");

                    b.ToTable("video_summaries", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.VideoTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Dil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("tr")
                        .HasColumnName("dil");

                    b.Property<string>("HamMetin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ham_metin");

                    b.Property<int>("KelimeSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kelime_sayisi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SttModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stt_model");

                    b.Property<int>("SttSuresiMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stt_suresi_ms");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("ZamanDamgalari")
                        .HasColumnType("jsonb")
                        .HasColumnName("zaman_damgalari");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("idx_video_transcripts_video_id");

                    b.ToTable("video_transcripts", (string)null);
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.ContentRequest", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.Egitim", "Egitim")
                        .WithMany("ContentRequests")
                        .HasForeignKey("EgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_requests_egitim");

                    b.Navigation("Egitim");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.GeneratedContent", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.ContentRequest", "ContentRequest")
                        .WithOne("GeneratedContent")
                        .HasForeignKey("VideoOzet.Data.Entities.GeneratedContent", "ContentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_contents_request");

                    b.Navigation("ContentRequest");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.QcResult", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.ContentRequest", "ContentRequest")
                        .WithOne("QcResult")
                        .HasForeignKey("VideoOzet.Data.Entities.QcResult", "ContentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qc_results_request");

                    b.Navigation("ContentRequest");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.Video", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.Egitim", "Egitim")
                        .WithMany("Videolar")
                        .HasForeignKey("EgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_videolar_egitim");

                    b.Navigation("Egitim");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.VideoSummary", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.Video", "Video")
                        .WithOne("Summary")
                        .HasForeignKey("VideoOzet.Data.Entities.VideoSummary", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_video");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.VideoTranscript", b =>
                {
                    b.HasOne("VideoOzet.Data.Entities.Video", "Video")
                        .WithOne("Transcript")
                        .HasForeignKey("VideoOzet.Data.Entities.VideoTranscript", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcripts_video");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.ContentRequest", b =>
                {
                    b.Navigation("GeneratedContent");

                    b.Navigation("QcResult");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.Egitim", b =>
                {
                    b.Navigation("ContentRequests");

                    b.Navigation("Videolar");
                });

            modelBuilder.Entity("VideoOzet.Data.Entities.Video", b =>
                {
                    b.Navigation("Summary");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
