<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-VideoOzet.Worker-bee4307c-4b2b-4293-9dde-e7602b8c8b1b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.4" />
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.5.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="Quartz" Version="3.17.1" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoOzet.Business\VideoOzet.Business.csproj" />
    <ProjectReference Include="..\VideoOzet.Data\VideoOzet.Data.csproj" />
  </ItemGroup>
</Project>
